Repository eclipse-uprotocol/up-transport-mqtt5-rust, pull requests merged in 2025-01, with the labels that each got.

#19 Include integration tests in CI
  .github/workflows/lint-and-test.yaml
Labels: enhancement

#21 Improve unit tests
  Cargo.toml
  src/lib.rs
  src/transport.rs
Labels: enhancement

#24 Fix nightly build's MSRV check
  .github/workflows/verify-msrv.yaml
Labels: bug, CI/CD

#17 add correct message expiry
  examples/publisher_example.rs
  examples/subscriber_example.rs
  src/lib.rs
Labels: enhancement, breaking change
