Repository eclipse-uprotocol/up-transport-mqtt5-rust, pull requests merged in 2025-03, with the labels that each got.

#37 Improve stability of CI jobs
  .github/workflows/nightly.yaml
  .gitignore
  Cargo.lock
  Cargo.toml
Labels: CI/CD

#39 Subscribtion recreation
  src/mqtt_client.rs
Labels: enhancement

#42 Add missing license headers
  .github/scripts/check-3rd-party-licenses.sh
  tests/common/mod.rs
  tests/mosquitto/docker-compose.yaml
  tests/mosquitto/mosquitto.conf
  tests/publish_subscribe.rs
Labels: documentation

#40 Improve CI job for running tests
  .config/nextest.toml
  .github/workflows/check.yaml
Labels: CI/CD

#41 Add references to OpenFastTrace specification items
  README.md
  src/lib.rs
  src/listener_registry.rs
  src/mapping.rs
  src/transport.rs
Labels: documentation

#44 Upgrade to up-rust 0.5.0
  Cargo.lock
  Cargo.toml
  deny.toml
  src/mqtt_client.rs
Labels: enhancement

#47 Fix expiration check of deserialized message
  src/mapping.rs
Labels: bug

#48 Use shared Dash Licenses tool Action
  .github/scripts/check-3rd-party-licenses.sh
  .github/workflows/check-dependencies.yaml
Labels: CI/CD
